version: "3.0"
services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    entrypoint: "/var/www/app/docker/startup.sh"
    command: "echo hey im here && which httpd && httpd -DFOREGROUND"
    depends_on:
      - database
    environment:
      APP_DIR: /var/www/app
      VCAP_APPLICATION: >
        {
          "fake": "yes",
          "application_name": "app",
          "name": "app",
          "uris": [
            "localhost:8000"
          ]
        }
      VCAP_SERVICES: >
        {
          "aws-rds": [
            {
              "name": "database",
              "credentials": {
                "db_name": "dashboard",
                "host": "database",
                "password": "mysql",
                "port": "3306",
                "username": "root"
              }
            }
          ],
          "s3": [
          {
            "binding_name": null,
            "credentials": {
            "access_key_id": "SOME_ACCESS_KEY_ID",
            "additional_buckets": [],
            "bucket": "SOME_BUCKET_ID",
            "region": "us-gov-west-1",
            "secret_access_key": "SOME_SECRET_ACCESS_KEY",
            "uri": "s3://some-long-uri"
            },
            "instance_name": "s3",
            "label": "s3",
            "name": "s3",
            "plan": "basic-sandbox",
            "provider": null,
            "syslog_drain_url": null,
            "tags": [
            "AWS",
            "S3",
            "object-storage"
            ],
            "volume_mounts": []
          }
          ],
          "user-provided": [
            {
              "name": "secrets",
              "credentials": {
                "ENCRYPTION_KEY": "not-a-real-key-from-vcap",
                "NEWRELIC_LICENSE": "another-dummy-value"
              }
            }
          ]
        }
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/app:delegated
      - uploads:/var/www/app/uploads

  database:
    image: mysql:5.7
    platform: linux/x86_64
    volumes:
      - database_data:/var/lib/mysql:delegated
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: dashboard

volumes:
  database_data:
  uploads:
